project:
  type: website
  output-dir: docs

website:
  title: "Abdoulie Jallow"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - posts.qmd # Add listing page to the navbar
      - projects.qmd
      - href: CV/AJallow_CV.pdf
        text: CV
        target: _blank # opens link (or page) in a new browser tab
      - icon: github
        href: https://github.com/jallow-code
        target: _blank
  page-footer:
    left: © 2024 Abdoulie Jallow
    right: This website is build with [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/jallow-code/jallow-code.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme:
      light: styles/light-theme.scss
      dark: styles/dark-theme.scss
    css: styles/ek-styles.css
    smooth-scroll: true
    link-external-newwindow: true  
    toc: true
    page-layout: full
highlight-style: gruvbox
code-block-border-left: "#31BAE9"



editor: visual

