project:
  type: website
  output-dir: docs

website:
  title: "Abdoulie Jallow"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd

format:
  html:
    theme:
      light: solar
      dark: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

